sudo: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean compile test package scripted
scala:
  - 2.11.7

jdk:
  - oraclejdk8

notifications:
  email:
    - lukasz.stefaniak@blstream.com

after_success:
  - if [ -n "$TRAVIS_TAG" -o "$TRAVIS_BRANCH" == "master" ]; then sbt publish; fi