sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean compile test:compile
scala:
  - 2.11.7

jdk:
  - oraclejdk8

notifications:
  email:
    - lukasz.stefaniak@blstream.com