sudo: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala
script:
  - git config --global user.email "travis@example.com"
  - git config --global user.name "Travis CI"
  - if [[ -z $(git rebase origin/master) ]]; then echo "Can't be cleanly merged with origin/master" && exit 1 ; fi
  - sbt formatAll
  - if [[ -n $(git status -s) ]]; then git status && echo 'You need to format your code!' && exit 1; fi
  - ./.bintray_setup_credentials.sh
  - sbt clean compile package
  - sbt "set coverageEnabled in monitoring := true" test scripted
  - sbt monitoring/coverageReport monitoring/codacyCoverage
  - rm -r -f $HOME/.ivy2/local/

jdk:
  - oraclejdk8

notifications:
  email:
    - lukasz.stefaniak@blstream.com

after_success:
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ -n "$TRAVIS_TAG" -o "$TRAVIS_BRANCH" == "master" ]; then sbt publish; fi
  - bash <(curl -s https://codecov.io/bash)